### ISSUE TITLE
The viade_en2a group links are not right

### ISSUE THREAD

**Issue by Angelixus** [Arquisoft/Arquisoft.github.io#30]
On the student projects [webpage](https://arquisoft.github.io/course1920.html#StudentProjects) if I try to open the links for viade_en2a they link to viade_en2b pages

**Comment by labra** [comment]
You are right, you can change it when you do the pull request.

Regards, Jose Labra

**Comment by Angelixus** [comment]
@labra I already created the pull request with the presentation and link fix, you can see it here #31

**Comment by labra** [comment]
Thanks 👍
