### ISSUE TITLE
Lab resources Day 1 (page not found)

### ISSUE THREAD

**Issue by Rcenador** [Arquisoft/Arquisoft.github.io#64]
The links to the pdfs related to Lab1 are broken. 
Possible cause: the name of the files (lines 245&246):

https://github.com/Arquisoft/Arquisoft.github.io/blob/c9732e86a8b74a8b3cd1fd019e36a0e078e5f696/course2021.html#L245-L246

Possible solution: rename the files -> EN.ASW.PL01_Github_2021.pdf & ES.ASW.PL01_Github_2021.pdf

**Comment by labra** [comment]
Thanks a lot! 😄 

It has been repaired.
